---
title: "PS Assignment"
author: "Josh Jacobs"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(MatchIt)
library(tableone)
library(survey)
library(reshape2)
```

## Import data
```{r}
NHEFS_1 <- read_excel("NHEFS-1.xls")
```

## Data Manipulation
```{r}

#restrict analysis to those who were alove at both time points
NHEFS_1 <- NHEFS_1 %>% 
  filter(!is.na(wt82))

#create unique study ID and remove outcome
NHEFS_no_outcome<- NHEFS_1 %>% 
  rename(studyid= seqn) %>% 
  select(-wt82_71) 

NHEFS_outcome<- NHEFS_1 %>% 
  rename(studyid= seqn) 

#assessing structure and missingness in variables
str(NHEFS_1)
summary(NHEFS_1)
```

## Building PS model
```{r}
model1_pre <- glm(qsmk~active + age + alcoholfreq + alcoholpy + asthma + birthcontrol + birthplace + bronch + cholesterol + chroniccough + dbp + diabetes + education + exercise + hbp + hbpmed + hf + income + marital + nerves + nervousbreak + otherpain + race + sbp + school + sex + smokeintensity + smokeyrs + tumor + weakheart + boweltrouble + colitis + pepticulcer + polio + wtloss +wt71, family="binomial", data=NHEFS_no_outcome)
```

## Create PS and check overlap
```{r}
NHEFS_no_outcome$ps <- predict(model1_pre, NHEFS_no_outcome, type="response")

NHEFS_no_outcome <- NHEFS_no_outcome %>% mutate(qsmklabel = ifelse(qsmk == 1,
                       yes = 'Quit Smoking 1971-1982',
                       no = 'Did Not Quit Smoking 1971-1982'))

ggplot(NHEFS_no_outcome, aes(x = ps, fill = as.factor(qsmklabel), color = as.factor(qsmklabel))) +
  geom_histogram(alpha = 0.3, position = 'identity', bins=15) +
  facet_grid(as.factor(qsmk) ~ .) +
  xlab('Probability of Quitting Smoking During Follow-up') +
  ggtitle('Propensity Score Distribution by Treatment Group') +
  scale_fill_discrete('') +
  scale_color_discrete('') +
  theme(legend.position = 'bottom', legend.direction = 'vertical')
```

## Creating balancing table for unadjusted
```{r}

# creating variables object
vars <- c("active", "age", "alcoholfreq", "alcoholpy", "asthma", "birthcontrol", "birthplace", "bronch", "cholesterol", "chroniccough", "dbp", "diabetes", "education", "exercise", "hbp", "hbpmed", "hf", "income", "marital", "nerves",  "nervousbreak", "otherpain", "race", "sbp", "school", "sex", "smokeintensity",  "smokeyrs", "tumor", "weakheart", "boweltrouble", "colitis", "pepticulcer", "polio", "wtloss", "wt71")

# unmadjusted

## Construct a table
tabUnmatched <- CreateTableOne(vars = vars, strata = "qsmklabel", data = NHEFS_no_outcome, test = FALSE)

## Show table with SMD
tabUnmatched_smd<- print(tabUnmatched, smd = TRUE)
write.csv(tabUnmatched_smd, file="tabUnmatched.csv")
```
## Overlap weighting
```{r}
# Adusted

## treatment actually assigned 

NHEFS_no_outcome$ps_no <- 1 - NHEFS_no_outcome$ps

NHEFS_no_outcome$pAssign <- NA

NHEFS_no_outcome$pAssign[NHEFS_no_outcome$qsmk==1]<- NHEFS_no_outcome$ps[NHEFS_no_outcome$qsmk==1]

NHEFS_no_outcome$pAssign[NHEFS_no_outcome$qsmk==0] <- NHEFS_no_outcome$ps_no[NHEFS_no_outcome$qsmk==0]

# creating overlap weights
NHEFS_no_outcome$ow <- (NHEFS_no_outcome$pAssign * (1 - NHEFS_no_outcome$pAssign)) / NHEFS_no_outcome$pAssign

# remove those with missing weights
NHEFS_no_outcome <- NHEFS_no_outcome %>% 
  filter(!is.na(ow))

## Weighted data
NHEFS_no_outcomeSvyOw <- svydesign(ids = ~ 1, data = NHEFS_no_outcome, 
                                   weights = ~ow)

## Construct a table
tabWeightedOw <- svyCreateTableOne(vars = vars, strata = "qsmklabel", data = NHEFS_no_outcomeSvyOw, test = FALSE)
## Show table with SMD
tabWeightedOw_smd <- print(tabWeightedOw, smd = TRUE)
write.csv(tabWeightedOw_smd, file="tabWeightedOw.csv")
```

## Plotting balance
```{r}
## Construct a data frame containing variable name and SMD from all methods
dataPlot <- data.frame(variable   = rownames(ExtractSmd(tabUnmatched)),
                       Unmatched  = as.numeric(ExtractSmd(tabUnmatched)),
                       WeightedOw = as.numeric(ExtractSmd(tabWeightedOw)))

## Create long-format data for ggplot2
dataPlotMelt <- melt(data          = dataPlot,
                     id.vars       = c("variable"),
                     variable.name = "Method",
                     value.name    = "SMD")

## Order variable names by magnitude of SMD
varNames <- as.character(dataPlot$variable)[order(dataPlot$Unmatched)]

## Order factor levels in the same order
dataPlotMelt$variable <- factor(dataPlotMelt$variable,
                                levels = varNames)

## Plot using ggplot2
ggplot(data = dataPlotMelt,
       mapping = aes(x = variable, y = SMD, group = Method, color = Method)) +
    geom_line() +
    geom_point() +
    geom_hline(yintercept = 0.1, color = "black", size = 0.1) +
    coord_flip() +
    theme_bw() +
    theme(legend.key = element_blank())
```

## Merging no outcome table with outcome table now
```{r}
NHEFS_merged <- merge(NHEFS_no_outcome,NHEFS_outcome)
```


## Crude regression
```{r}
lmCrude <- lm(wt82_71~qsmk, data=NHEFS_outcome)
summary(lmCrude)
confint(lmCrude)
```

## Multivariable regression
```{r}
lmadjusted <- lm(wt82_71~qsmk + age + alcoholfreq + alcoholpy + asthma + birthcontrol + birthplace + bronch + cholesterol + chroniccough + dbp + diabetes + education + exercise + hbp + hbpmed + hf + income + marital + nerves + nervousbreak + otherpain + race + sbp + school + sex + smokeintensity + smokeyrs + tumor + weakheart, data=NHEFS_outcome)
length(lmadjusted$residuals)
summary(lmadjusted)
confint(lmadjusted)
```

## Regression for overlap weighting
```{r}

# drop missing values again
NHEFS_merged <- NHEFS_merged %>% 
  filter(!is.na(ow))

# format data into design
NHEFS_mergedSvyOw <- svydesign(ids = ~ 1, data = NHEFS_merged, 
                                   weights = ~ow)

# actual regression
lmWeighted <- svyglm(formula = wt82_71 ~ qsmk,
                      design  = NHEFS_mergedSvyOw)
summary(lmWeighted)
confint(lmWeighted)
```



## Empty Chunk
```{r}

```

## Empty Chunk
```{r}

```

## Empty Chunk
```{r}

```

## Empty Chunk
```{r}

```

## Empty Chunk
```{r}

```